articles/urls.py
from django.urls import path 
from . import views 

app_name = 'articles'
# /articles/__ 
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),  # url 에 이름 짓기 
    path('<int:article_pk>/delete/', views.delete, name='delete'),  
    path('create/', views.create, name='create'),  # mapping
    path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('selected/', views.selected, name='selected'), 
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    # /article/3/commnets/2/delete
    path('<int:comment_pk>/comments_delete/', views.comments_delete, name='comments_delete'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    # articles 로 들어왔다면 articles/urls.py 로 이동해
    path('articles/', include('articles.urls')),
    path('jobs/', include('jobs.urls')),
    path('admin/', admin.site.urls),
    # static('/media/', 'BASE_DIR/media'),
]

# 사용자가 Media 파일이 있는 곳으로 올 수 있는 경로를 추가한다.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path 
from . import views 

app_name = 'jobs'
urlpatterns = [
    path('', views.index, name='index'),
    path('past_job/', views.past_job, name='past_job'),
]

articles/models.py
from django.db import models
from imagekit.processors import Thumbnail
from imagekit.models import ImageSpecField


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    # blank vs null 
    # blank: 데이터 유효성과 관련되어 있다. (비어있어도 상관없어)
    # null: DB와 관련되어 있다. (DB 에 Null 로 저장할건지에 대한 여부 확인)
    # django 에서 textfiled 는 '' 
    image = models.ImageField(blank=True)  # chr 형식으로 들어감 그래서 null True 삭제 / 비어있는 str 이 들어가 있는 상태 
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(50, 50)],
        format='JPEG',
        options={'quality': 90},
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

class Comment(models.Model):
    # on_delete=models.CASCADE == 'Article 이 삭제되면 Comment 도 함께 삭제'
    # article.comments 는 어떻게... related_name='comments' / default = comment_set
    # article.comments.all()
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 역순으로 가져올 수 있도록 
    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.content

jobs/models.py
from django.db import models


class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()
    profile_image = models.ImageField(blank=True)

    def __str__(self):
        return self.name

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment


# articles 의 메인 페이지, article list 를 보여 줌 
def index(request):
    # SELECT * FROM Article
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    # render 는 url 과 상관없다. 
    return render(request, 'articles/index.html', context)


def detail(request, article_pk):
    # SELECT * FROM articles WHERE pk = article_pk
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comments.all()
    context = {
        'article': article,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


# GET method 로 delete 를 하면 안되는 이유
# 아무나? 
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        article.delete()
    # redirect 는 url 과 상관있다.
    # 다른 app 과 name 이 중복되면?  
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)


# 데이터를 전달 받아서 article 생성
# POST /articles/create/
# REST API 는 방법론 / 해당 자원에 대한 표현 URI / 행동 METHOD 
def create(request):
    # 아니라면 (POST 일 경우) 사용자 데이터 받아서 article 생성
    if request.method == 'POST':
        # POST 로 바뀌었으니 더 이상 GET 이 아니다! 
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        article = Article(title=title, content=content, image=image)
        article.save()
        # 작성 후 상세페이지 바로가기 
        # : 뒤에 띄어쓰지 말것 
        return redirect('articles:index')
        # return redirect('articles:detail', article.pk )
    # 만약 GET 요청으로 들어오면 html 페이지 rendering
    else:
        return render(request, 'articles/create.html')


def edit(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        if image:
            article.image = image
        article.title = title
        article.content = content
        article.save()
        return redirect('articles:detail', article.pk)
    else:
        context = {
            'article': article,
        }
        return render(request, 'articles/edit.html', context)


def selected(request):
    chks = request.POST.getlist('chk')
    for chk in chks:
        article = Article(pk=chk)
        article.delete()
    return redirect('articles:index')


def comments_create(request, article_pk):
    # article_pk 에 해당하는 article 에 새로운 comment 생성
    # 생성한 다음 article detail page 로 redirect
    article = get_object_or_404(Article, pk=article_pk)
    # POST 요청일 때만 가능하게 
    if request.method == 'POST':
        content = request.POST.get('content')
        comment = Comment()
        comment.content = content
        comment.article = article
        # comment.article_id = article_pk 
        comment.save()
    return redirect('articles:detail', article.pk)

    # article = comment.article 로 해당 article 을 가져올수있음
    # article.comment_set.all() artcle 에 달려있는 comment 들을 가져올수있음  


def comments_delete(request, comment_pk):
    # comment = get_object_or_404(Comment, pk=comment_pk)
    if request.method == 'POST':
        comment = Comment.objects.get(pk=comment_pk)
        article_pk = comment.article_id
        comment.delete()
    return redirect('articles:detail', article_pk)

jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Job
from faker import Faker
import requests
from pprint import pprint

Url = 'https://api.giphy.com/v1/gifs/search?api_key=rBmbyDm4lYUOqpUet86sNwmDjRucRfSL&lang=ko&limit=1&q='


def index(request):
    return render(request, 'jobs/index.html')


def past_job(request):
    fake = Faker()
    name = request.POST.get('name')
    image = request.FILES.get('image')
    # if image == None:
    #     image = '사진을 넣어주세요'
    
    # Job.objects.filter(name=name).first()

    if Job.objects.filter(name=name):
        job = Job.objects.get(name=name)
        if job.profile_image == '':
            job.profile_image = image
            job.save()
    else:
        job = Job()
        job.name = name
        job.past_job = fake.job()
        job.profile_image = image
        job.save()
    url = Url + job.past_job
    data = requests.get(url).json()
    try:
        data = data.get('data')[0].get('images').get('downsized').get('url')
    except:
        data = 'No image'
    context = { 
        'job': job,
        'data': data, 
    }
    return render(request, 'jobs/past_job.html', context)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block body %}
  <h1>New Article</h1>
  {% comment %} method default = GET {% endcomment %}
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title"><br><br>
    <textarea name="content" cols="30" rows="10"></textarea><br><br>
    <label for="image">이미지:</label>
    <input type="file" name="image" id="image" accept="image/*"><br><br>
    <button type="submit">생성하기</button>
  </form>
  <a href="{% url 'articles:index' %}">[뒤로가기]</a>
{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article Detail {{ article.pk }}{% endblock title %}

{% block body %}
  <h1>{{ article.title }}</h1>
  <p>작성일자: {{ article.created_at }}</p>
  <hr>
  {% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  <p>{{ article.content }}</p>
  <form action="{% url 'articles:edit' article.pk %}">
    {% csrf_token %}
    <button type="submit">수정하기</button>
  </form>
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('Are you sure?')">
    {% csrf_token %}
    <button type="submit">삭제하기</button>
  </form>
  <a href="{% url 'articles:index' %}">[뒤로가기]</a>
  <hr>
  <p>-댓글-</p>
  {% comment %} 댓글 작성을 위한 form {% endcomment %}
  <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="text", name="content">
    <button type="submit">댓글 작성</button>
  </form>
  <ul>
  {% for comment in comments %}
    <li>
      {{ comment.pk }}. {{ comment.content }}
      <form action="{% url 'articles:comments_delete' comment.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">삭제하기</button>
      </form>
    </li>
    {% empty %}
      <p>아직 댓글이 없습니다...</p>
  {% endfor %}
  </ul>
{% endblock body %}

articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block title %}Edit Article{% endblock title %}

{% block body %}
  <h1>Edit Article</h1>
  {% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  {% comment %} 오타주의 {% endcomment %}
  <form action="{% url 'articles:edit' article.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title" value="{{ article.title }}"><br><br>
    <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea><br><br>
    {% comment %} 파일을 value로 미리 값을 넣지 못함 {% endcomment %}
    <label for="image">이미지: </label>
    <input type="file" name="image" id="image" accept="image/*"><br><br>
    <button type="submit">수정하기</button>
  </form>
  <a href="{% url 'articles:detail' article.pk %}">[뒤로가기]</a>
{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% comment %} static 파일들을 불러오겠다. {% endcomment %}
{% load static %}

{% block title %}Articles{% endblock title %}

{% block body %}
  {% comment %} url 을 만들어 주는 태그 {% endcomment %}
  {% comment %} 리소스에 바로 접근하지 못하도록 {% endcomment %}
  <img src="{% static 'articles/images/Scarlet.jpg' %}" alt="SCARLET">
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">[작성하기]</a>
  <hr>
  <form action="{% url 'articles:selected' %}" method="POST">
    {% csrf_token %}
    {% for article in articles %}
    <br>
    <div>
      {% if article.image %}
        <img src="{{ article.image_thumbnail.url }}" alt="{{ article.image }}">
      {% endif %}
      <h3><a href="{% url 'articles:detail' article.pk %}">{{ article.pk }}. {{ article.title }}</a></h3>
      <p>{{ article.content }}</p>
      <input type="checkbox" name="chk" value="{{ article.pk }}">
    </div>
    {% endfor %}
    <br>
    <button type="submit">선택 글 삭제하기</button>
  </form>
{% endblock body %}

articles/templates/articles/new.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block body %}
  <h1>New Article</h1>
  <form action="{% url 'articles:create' %}">
    <input type="text" name="title"><br><br>
    <textarea name="content" cols="30" rows="10"></textarea><br><br>
    <button type="submit">생성하기</button>
  </form>
{% endblock body %}

crud/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'base.css' %}">
  <link rel="shortcut icon" href="{% static 'favicon-96x96.png' %}" type="image/x-icon">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  {% block body %}
  {% endblock body %}
</body>
</html>

jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block title %}이름 입력{% endblock title %}

{% block body %}
  <h1>이름 입력</h1>
  <form action="{% url 'jobs:past_job' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name"><br><br>
    <label for="image">이미지:</label>
    <input type="file" name="image" id="image" accept="image/*"><br><br>
    <button type="submit">생성하기</button>
  </form>
{% endblock body %}

jobs/templates/jobs/past_job.html
{% extends 'base.html' %}

{% block title %}결과{% endblock title %}

{% block body %}
  <h1>{{ job.past_job }}</h1>
  <h2><img src="{{ data }}" alt=""></h2>
  {% if job.profile_image %}
    <img src="{{ job.profile_image.url }}" alt="{{ job.profile_image }}">
  {% endif %}
{% endblock body %}